# Generated by Django 5.2.1 on 2026-02-07 17:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideLateralRaise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_reps', models.PositiveIntegerField(default=12)),
                ('total_reps', models.PositiveIntegerField()),
                ('excellent_reps', models.PositiveIntegerField(default=0)),
                ('good_reps', models.PositiveIntegerField(default=0)),
                ('partial_reps', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_lateral_sessions', to='Patients.patient')),
            ],
        ),
    ]
