# Generated by Django 5.2.1 on 2026-02-07 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0004_sls_delete_sidelateralraises'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sls',
            options={'ordering': ['-created_at'], 'verbose_name': 'SLS Workout', 'verbose_name_plural': 'SLS Workouts'},
        ),
        migrations.AddField(
            model_name='sls',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sls',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Workout duration in seconds'),
        ),
        migrations.AddField(
            model_name='sls',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sls',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sls',
            name='excellent_reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sls',
            name='good_reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sls',
            name='partial_reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sls',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sls_workouts', to='Patients.patient'),
        ),
        migrations.AlterField(
            model_name='sls',
            name='target_reps',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='sls',
            name='total_reps',
            field=models.IntegerField(default=0),
        ),
    ]
